<!DOCTYPE data-dictionary [
        <!ELEMENT data-dictionary (statement-execution-processor)*>
        <!ELEMENT statement-execution-processor (statement)*>
        <!ATTLIST statement-execution-processor
                id CDATA #REQUIRED
                is-query CDATA #IMPLIED
                is-prepared-statement CDATA #IMPLIED
                timeout CDATA #IMPLIED>
        <!ELEMENT statement (#PCDATA)>
        <!ATTLIST statement
                comment CDATA #IMPLIED
                prefixes CDATA #IMPLIED>
        ]>
<data-dictionary>
    <statement-execution-processor id="users" is-query="true" is-prepared-statement="true">
        <statement>
            select
                USERNAME as USER_NAME,
                case when ACCOUNT_STATUS like '%EXPIRED%' then 'Y' else 'N' end as IS_EXPIRED,
                case when ACCOUNT_STATUS like '%LOCKED%' then 'Y' else 'N' end as IS_LOCKED
            from DBA_USERS
        </statement>
        <statement>
            select
                USERNAME as USER_NAME,
                'N' as IS_EXPIRED,
                'N' as IS_LOCKED
            from ALL_USERS
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="roles" is-query="true" is-prepared-statement="true">
        <statement>
            select distinct ROLE as ROLE_NAME from DBA_ROLES
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="all-user-roles" is-query="true" is-prepared-statement="true">
        <statement>
            select
                rp.GRANTEE as USER_NAME,
                rp.GRANTED_ROLE as GRANTED_ROLE_NAME,
                rp.ADMIN_OPTION as IS_ADMIN_OPTION,
                rp.DEFAULT_ROLE as IS_DEFAULT_ROLE
            from
                DBA_ROLE_PRIVS rp,
                DBA_USERS u
            where rp.GRANTEE = u.USERNAME
            order
                by rp.GRANTEE,
                rp.GRANTED_ROLE asc
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="all-role-roles" is-query="true" is-prepared-statement="true">
        <statement>
            select
                rp.GRANTEE as ROLE_NAME,
                rp.GRANTED_ROLE as GRANTED_ROLE_NAME,
                rp.ADMIN_OPTION as IS_ADMIN_OPTION,
                rp.DEFAULT_ROLE as IS_DEFAULT_ROLE
            from
                DBA_ROLE_PRIVS rp,
                DBA_ROLES r
            where rp.GRANTEE = r.ROLE
            order
                by rp.GRANTEE,
                rp.GRANTED_ROLE asc
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="system-privileges" is-query="true" is-prepared-statement="true">
        <statement>
            select distinct PRIVILEGE as PRIVILEGE_NAME from DBA_SYS_PRIVS
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="all-user-privileges" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                sp.GRANTEE as USER_NAME,
                sp.PRIVILEGE as GRANTED_PRIVILEGE_NAME,
                sp.ADMIN_OPTION as IS_ADMIN_OPTION
            from
                DBA_SYS_PRIVS sp,
                [PREFIX]_USERS u
            where sp.GRANTEE = u.USERNAME
            order by
                sp.GRANTEE,
                sp.PRIVILEGE asc
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="all-role-privileges" is-query="true" is-prepared-statement="true">
        <statement>
            select
                sp.GRANTEE as ROLE_NAME,
                sp.PRIVILEGE as GRANTED_PRIVILEGE_NAME,
                sp.ADMIN_OPTION as IS_ADMIN_OPTION
            from
                DBA_SYS_PRIVS sp,
                DBA_ROLES r
            where sp.GRANTEE = r.ROLE
            order by
                sp.GRANTEE,
                sp.PRIVILEGE asc
        </statement>
    </statement-execution-processor>
    <statement-execution-processor id="schemas" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                u.USERNAME as SCHEMA_NAME,
                'N' as IS_PUBLIC,
                decode(u.USERNAME, 'SYS', 'Y', 'SYSTEM', 'Y', 'N') as IS_SYSTEM,
                decode (count(o.OWNER), 0, 'Y', 'N') as IS_EMPTY
            from [PREFIX]_USERS u, [PREFIX]_OBJECTS o
            where u.USERNAME = o.OWNER (+)
            group by USERNAME
            union (
                select
                    'PUBLIC',
                    'Y' as IS_PUBLIC,
                    'Y' as IS_SYSTEM,
                    'N' as IS_EMPTY
                from DUAL)
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="clusters" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select CLUSTER_NAME
            from [PREFIX]_CLUSTERS
            where OWNER = {0}
            order by CLUSTER_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="tables" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                TABLE_NAME,
                TEMPORARY as IS_TEMPORARY
            from  [PREFIX]_ALL_TABLES
            where OWNER = {0}
            minus
            select
                MVIEW_NAME as TABLE_NAME,
                'N' as IS_TEMPORARY
            from [PREFIX]_MVIEWS
            where OWNER = {0}
            order by TABLE_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="views" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                VIEW_NAME,
                VIEW_TYPE_OWNER,
                VIEW_TYPE,
                'N' as IS_SYSTEM_VIEW
            from [PREFIX]_VIEWS
            where OWNER = {0}
            order by VIEW_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="materialized-views" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                MVIEW_NAME as VIEW_NAME,
                null as VIEW_TYPE_OWNER,
                null as VIEW_TYPE,
                'N' as IS_SYSTEM_VIEW
            from [PREFIX]_MVIEWS
            where OWNER = {0}
            order by MVIEW_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="dataset-columns" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                col.COLUMN_NAME,
                col.COLUMN_ID as POSITION,
                null as DATA_TYPE_PACKAGE,
                col.DATA_TYPE_OWNER,
                col.DATA_TYPE as DATA_TYPE_NAME,
                col.DATA_LENGTH,
                col.DATA_PRECISION,
                col.DATA_SCALE,
                'N' as IS_SET,
                col.NULLABLE as IS_NULLABLE,
                decode (col.HIDDEN_COLUMN, 'YES', 'Y', 'N' ) as IS_HIDDEN,
                decode (pk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_PRIMARY_KEY,
                decode (fk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_FOREIGN_KEY,
                decode (uk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_UNIQUE_KEY
            from [PREFIX]_TAB_COLS col,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'P') pk,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'R') fk,
                 (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'U') uk
            where
                col.OWNER = {0} and
                col.TABLE_NAME = {1} and
                col.OWNER = pk.OWNER(+) and
                col.TABLE_NAME = pk.TABLE_NAME(+) and
                col.COLUMN_NAME = pk.COLUMN_NAME(+) and
                col.OWNER = fk.OWNER(+) and
                col.TABLE_NAME = fk.TABLE_NAME(+) and
                col.COLUMN_NAME = fk.COLUMN_NAME(+) and
                col.OWNER = uk.OWNER(+) and
                col.TABLE_NAME = uk.TABLE_NAME(+) and
                col.COLUMN_NAME = uk.COLUMN_NAME(+)
            order by col.COLUMN_NAME asc
        </statement>
        <statement prefixes="DBA, ALL" comment="Oracle 8.0">
            select
                col.COLUMN_NAME,
                col.COLUMN_ID as POSITION,
                null as DATA_TYPE_PACKAGE,
                col.DATA_TYPE_OWNER,
                col.DATA_TYPE as DATA_TYPE_NAME,
                col.DATA_LENGTH,
                col.DATA_PRECISION,
                col.DATA_SCALE,
                'N' as IS_SET,
                col.NULLABLE as IS_NULLABLE,
                'N' as IS_HIDDEN,
                decode (pk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_PRIMARY_KEY,
                decode (fk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_FOREIGN_KEY,
                decode (uk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_UNIQUE_KEY
            from [PREFIX]_TAB_COLUMNS col,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'P') pk,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'R') fk,
                 (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'U') uk
            where
                col.OWNER = {0} and
                col.TABLE_NAME = {1} and
                col.OWNER = pk.OWNER(+) and
                col.TABLE_NAME = pk.TABLE_NAME(+) and
                col.COLUMN_NAME = pk.COLUMN_NAME(+) and
                col.OWNER = fk.OWNER(+) and
                col.TABLE_NAME = fk.TABLE_NAME(+) and
                col.COLUMN_NAME = fk.COLUMN_NAME(+) and
                col.OWNER = uk.OWNER(+) and
                col.TABLE_NAME = uk.TABLE_NAME(+) and
                col.COLUMN_NAME = uk.COLUMN_NAME(+)
            order by col.COLUMN_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-dataset-columns" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                col.TABLE_NAME as DATASET_NAME,
                col.COLUMN_NAME,
                col.COLUMN_ID as POSITION,
                null as DATA_TYPE_PACKAGE,
                col.DATA_TYPE_OWNER,
                col.DATA_TYPE as DATA_TYPE_NAME,
                col.DATA_LENGTH,
                col.DATA_PRECISION,
                col.DATA_SCALE,
                'N' as IS_SET,
                col.NULLABLE as IS_NULLABLE,
                decode (col.HIDDEN_COLUMN, 'YES', 'Y', 'N' ) as IS_HIDDEN,
                decode (pk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_PRIMARY_KEY,
                decode (fk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_FOREIGN_KEY,
                decode (uk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_UNIQUE_KEY
            from [PREFIX]_TAB_COLS col,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'P') pk,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'R') fk,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'U') uk
            where
                col.OWNER = {0} and
                col.OWNER = pk.OWNER(+) and
                col.TABLE_NAME = pk.TABLE_NAME(+) and
                col.COLUMN_NAME = pk.COLUMN_NAME(+) and
                col.OWNER = fk.OWNER(+) and
                col.TABLE_NAME = fk.TABLE_NAME(+) and
                col.COLUMN_NAME = fk.COLUMN_NAME(+) and
                col.OWNER = uk.OWNER(+) and
                col.TABLE_NAME = uk.TABLE_NAME(+) and
                col.COLUMN_NAME = uk.COLUMN_NAME(+)
            order by col.TABLE_NAME asc
        </statement>
        <statement prefixes="DBA, ALL" comment="Oracle 8.0">
            select
                col.TABLE_NAME as DATASET_NAME,
                col.COLUMN_NAME,
                col.COLUMN_ID as POSITION,
                null as DATA_TYPE_PACKAGE,
                col.DATA_TYPE_OWNER,
                col.DATA_TYPE as DATA_TYPE_NAME,
                col.DATA_LENGTH,
                col.DATA_PRECISION,
                col.DATA_SCALE,
                'N' as IS_SET,
                col.NULLABLE as IS_NULLABLE,
                'N' as IS_HIDDEN,
                decode (pk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_PRIMARY_KEY,
                decode (fk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_FOREIGN_KEY,
                decode (uk.CONSTRAINT_NAME, null, 'N', 'Y') as IS_UNIQUE_KEY
            from [PREFIX]_TAB_COLUMNS col,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'P') pk,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'R') fk,
                (select
                     cc.OWNER,
                     cc.TABLE_NAME,
                     cc.CONSTRAINT_NAME,
                     cc.COLUMN_NAME
                 from
                      [PREFIX]_CONSTRAINTS con,
                      [PREFIX]_CONS_COLUMNS cc
                 where
                      con.OWNER = cc.OWNER and
                      con.TABLE_NAME = cc.TABLE_NAME and
                      con.CONSTRAINT_NAME = cc.CONSTRAINT_NAME and
                      con.CONSTRAINT_TYPE = 'U') uk
            where
                col.OWNER = {0} and
                col.OWNER = pk.OWNER(+) and
                col.TABLE_NAME = pk.TABLE_NAME(+) and
                col.COLUMN_NAME = pk.COLUMN_NAME(+) and
                col.OWNER = fk.OWNER(+) and
                col.TABLE_NAME = fk.TABLE_NAME(+) and
                col.COLUMN_NAME = fk.COLUMN_NAME(+) and
                col.OWNER = uk.OWNER(+) and
                col.TABLE_NAME = uk.TABLE_NAME(+) and
                col.COLUMN_NAME = uk.COLUMN_NAME(+)
            order by col.TABLE_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="column-constraint-relations" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                COLUMN_NAME,
                CONSTRAINT_NAME,
                POSITION
            from [PREFIX]_CONS_COLUMNS
            where
                OWNER = {0} and
                TABLE_NAME = {1}
            order by COLUMN_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-column-constraint-relations" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
               TABLE_NAME as DATASET_NAME,
               COLUMN_NAME,
               CONSTRAINT_NAME,
               POSITION
            from [PREFIX]_CONS_COLUMNS
            where OWNER = {0}
            order by TABLE_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="column-index-relations" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                COLUMN_NAME,
                INDEX_NAME
            from [PREFIX]_IND_COLUMNS
            where
                TABLE_OWNER = {0} and
                TABLE_NAME = {1}
            order by COLUMN_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-column-index-relations" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                TABLE_NAME,
                COLUMN_NAME,
                INDEX_NAME
            from [PREFIX]_IND_COLUMNS
            where TABLE_OWNER = {0}
            order by TABLE_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-constraints" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                TABLE_NAME as DATASET_NAME,
                CONSTRAINT_NAME,
                case CONSTRAINT_TYPE
                    when 'C' then 'CHECK'
                    when 'P' then 'PRIMARY KEY'
                    when 'U' then 'UNIQUE'
                    when 'R' then 'FOREIGN KEY'
                    when 'V' then 'VIEW CHECK'
                    when 'O' then 'VIEW READONLY'
                end as CONSTRAINT_TYPE,
                R_OWNER as FK_CONSTRAINT_OWNER,
                R_CONSTRAINT_NAME as FK_CONSTRAINT_NAME,
                decode(STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,
                SEARCH_CONDITION as CHECK_CONDITION
            from [PREFIX]_CONSTRAINTS
            where OWNER = {0}
            order by
                TABLE_NAME,
                CONSTRAINT_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="constraints" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                CONSTRAINT_NAME,
                case CONSTRAINT_TYPE
                    when 'C' then 'CHECK'
                    when 'P' then 'PRIMARY KEY'
                    when 'U' then 'UNIQUE'
                    when 'R' then 'FOREIGN KEY'
                    when 'V' then 'VIEW CHECK'
                    when 'O' then 'VIEW READONLY'
                end as CONSTRAINT_TYPE,
                R_OWNER as FK_CONSTRAINT_OWNER,
                R_CONSTRAINT_NAME as FK_CONSTRAINT_NAME,
                decode(STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,
                SEARCH_CONDITION as CHECK_CONDITION
            from [PREFIX]_CONSTRAINTS
            where
                OWNER = {0} and
                TABLE_NAME = {1}
            order by CONSTRAINT_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="indexes" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                INDEX_NAME,
                decode(UNIQUENESS, 'UNIQUE', 'Y', 'N') as IS_UNIQUE,
                decode(STATUS, 'VALID', 'Y', 'N') as IS_VALID
            from [PREFIX]_INDEXES
            where
                OWNER = {0} and
                TABLE_NAME = {1}
            order by INDEX_NAME asc            
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-indexes" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                INDEX_NAME,
                TABLE_NAME,
                decode(UNIQUENESS, 'UNIQUE', 'Y', 'N') as IS_UNIQUE,
                decode(STATUS, 'VALID', 'Y', 'N') as IS_VALID
            from [PREFIX]_INDEXES
            where OWNER = {0}
            order by
                TABLE_NAME,
                INDEX_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="nested-tables" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                TABLE_NAME as NESTED_TABLE_NAME,
                PARENT_TABLE_COLUMN as TABLE_COLUMN,
                TABLE_TYPE_OWNER as DATA_TYPE_OWNER,
                TABLE_TYPE_NAME as DATA_TYPE_NAME
                from [PREFIX]_NESTED_TABLES
            where
                OWNER = {0} and
                PARENT_TABLE_NAME = {1}
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-nested-tables" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select
                TABLE_NAME as NESTED_TABLE_NAME,
                PARENT_TABLE_NAME as TABLE_NAME,
                PARENT_TABLE_COLUMN as TABLE_COLUMN,
                TABLE_TYPE_OWNER as DATA_TYPE_OWNER,
                TABLE_TYPE_NAME as DATA_TYPE_NAME
            from [PREFIX]_NESTED_TABLES
            where OWNER = {0}
            order by PARENT_TABLE_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="dataset-triggers" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select distinct
                t.TABLE_NAME as DATASET_NAME,
                t.TRIGGER_NAME,
                t.TRIGGER_TYPE,
                t.TRIGGERING_EVENT,
                decode(t.STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,
                decode(nvl(o.STATUS, 'VALID'), 'VALID', 'Y', 'N') as IS_VALID,
                decode(nvl(o.DEBUGINFO, 'F'), 'T', 'Y', 'N') as IS_DEBUG,
                case when t.TRIGGER_TYPE like '%EACH ROW%' then 'Y' else 'N' end as IS_FOR_EACH_ROW
            from
                [PREFIX]_TRIGGERS t,
                SYS.ALL_PROBE_OBJECTS o
            where
                t.TABLE_OWNER = {0} and
                t.TABLE_NAME = {1} and
                o.OWNER (+) = t.OWNER and
                o.OBJECT_NAME (+) = t.TRIGGER_NAME and
                o.OBJECT_TYPE (+)= 'TRIGGER'
            order by TRIGGER_NAME asc
        </statement>
        <statement prefixes="DBA, ALL">
            select distinct
                t.TABLE_NAME as DATASET_NAME,
                t.TRIGGER_NAME,
                t.TRIGGER_TYPE,
                t.TRIGGERING_EVENT,
                decode(t.STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,
                decode(o.STATUS, 'VALID', 'Y', 'N') as IS_VALID,
                'N' as IS_DEBUG,
                case when t.TRIGGER_TYPE like '%EACH ROW%' then 'Y' else 'N' end as IS_FOR_EACH_ROW
            from
                [PREFIX]_TRIGGERS t,
                [PREFIX]_OBJECTS o
            where
                o.OWNER = t.OWNER and
                o.OBJECT_NAME = t.TRIGGER_NAME and
                o.OBJECT_TYPE = 'TRIGGER' and
                t.TABLE_OWNER = {0} and
                t.TABLE_NAME = {1}
            order by TRIGGER_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="all-dataset-triggers" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select distinct
                t.TABLE_NAME as DATASET_NAME,
                t.TRIGGER_NAME,
                t.TRIGGER_TYPE,
                t.TRIGGERING_EVENT,
                decode(t.STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,
                decode(nvl(o.STATUS, 'VALID'), 'VALID', 'Y', 'N') as IS_VALID,
                decode(nvl(o.DEBUGINFO, 'F'), 'T', 'Y', 'N') as IS_DEBUG,
                case when t.TRIGGER_TYPE like '%EACH ROW%' then 'Y' else 'N' end as IS_FOR_EACH_ROW
            from
                [PREFIX]_TRIGGERS t,
                SYS.ALL_PROBE_OBJECTS o
            where
                t.TABLE_OWNER = {0} and
                t.BASE_OBJECT_TYPE in ('TABLE', 'VIEW') and
                o.OWNER (+) = t.OWNER and
                o.OBJECT_NAME (+) = t.TRIGGER_NAME and
                o.OBJECT_TYPE (+) = 'TRIGGER'
            order by
                t.TABLE_NAME,
                t.TRIGGER_NAME asc
        </statement>
        <statement prefixes="DBA, ALL">
            select distinct
                t.TABLE_NAME as DATASET_NAME,
                t.TRIGGER_NAME,
                t.TRIGGER_TYPE,
                t.TRIGGERING_EVENT,
                decode(t.STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,
                decode(o.STATUS, 'VALID', 'Y', 'N') as IS_VALID,
                'N' as IS_DEBUG,
                case when t.TRIGGER_TYPE like '%EACH ROW%' then 'Y' else 'N' end as IS_FOR_EACH_ROW
            from
                [PREFIX]_TRIGGERS t,
                [PREFIX]_OBJECTS o
            where
                o.OWNER = t.OWNER and
                o.OBJECT_NAME = t.TRIGGER_NAME and
                o.OBJECT_TYPE = 'TRIGGER' and
                t.TABLE_OWNER = {0} and
                t.BASE_OBJECT_TYPE in ('TABLE', 'VIEW' )
            order by
                TABLE_NAME,
                TRIGGER_NAME asc
        </statement>
    </statement-execution-processor>

    <statement-execution-processor id="database-triggers" is-query="true" is-prepared-statement="true">
        <statement prefixes="DBA, ALL">
            select distinct
            t.TRIGGER_NAME,
            t.TRIGGER_TYPE,
            t.TRIGGERING_EVENT,
            decode(t.STATUS, 'ENABLED', 'Y', 'N') as IS_ENABLED,